# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
