# Generated by Django 3.1.2 on 2020-10-20 18:33

import datetime
import dishes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug for category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField()),
                ('image', models.ImageField(height_field='height_field', upload_to=dishes.models.upload_location, verbose_name='Image', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preparing_time', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('for_vegan', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug for dish')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.category')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'ordering': ['-created_at'],
            },
        ),
    ]
