# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug for category'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug for dish'),
        ),
    ]
