# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='preparing_time',
            field=models.DurationField(default=datetime.timedelta(0, 300)),
        ),
    ]
